### ISSUE TITLE
Turbolinks 5 iOS auth

### ISSUE THREAD

**Issue by mityakoval** [thetizzo/thetizzo.github.io#1]
Hello Jason! We meet again :)
I have just found your blog post about Turbolinks 5 for iOS authentication. And it happens that I am still struggling with it. I can't figure out how do we tell our AuthController that it had authenticated successfully. I don't use Devise or anything for authentication in my Rails app. Instead I have the following `before_filter`: 

```
def require_login
  unless current_user
    redirect_to login_url, status: :unauthorized
  end
end
```

So it fires the error handling method in my iOS app and forces it to present AuthController.

Then the auth form is submitted remotely (according to [this](https://github.com/turbolinks/turbolinks-ios#handling-form-submission)) and Rails responds with `js.erb` file that does `Turbolinks.visit('whatever')`

But it doesn't dismiss the AuthController after the successful login.

I was trying to render that js-file with some success status code and check for it in iOS app, but there is no way to grab that code from Turbolinks unless it's an error (at least I couldn't find it). 

Do you have any thoughts?

**Comment by thetizzo** [comment]
I found that because the AuthController is separated from the rest of the views on the iOS side then you don't have to submit the form with XHR.  This way it closes the AuthController view in the app and loads your main Turbolinks enabled view controller.

**Comment by mityakoval** [comment]
Thanks a lot! It worked!
