### ISSUE TITLE
Log Out with Devise and Turbolinks iOS

### ISSUE THREAD

**Issue by carlesjove** [thetizzo/thetizzo.github.io#2]
Hi Jason,

I read your blog post on Authenticating with Devise and Turbolinks iOS. I've been struggling myself with Log Out and this rendering the Sign In page via the `AuthenticationController`. What I'm finding is that a regular `method: :delete, remote: true` ends up pushing the Sign In page into Turbolinks view stack. I've also tried POSTing, clearing Turbolink's cache after sign out… The only way I've found is setting a GET page to sign out which returns `401` and thus force `AuthenticationController`, but then Turbolinks attempts to restore the visit and it's not possible to log in anymore.

So I was wondering, how did you solve the log out scenario? Thanks :-)

**Comment by thetizzo** [comment]
I haven't built sign out yet unfortunately.  I would have thought that destroying the session on the server side and then redirecting the app to root path would put you back in the normal auth flow of getting a 401 from the app and loading the log in page.

I may try to implement this in the next couple weeks and see how it goes for me.  I'll update here if I have any success. 😄

**Comment by carlesjove** [comment]
Thanks for your reply. I managed to get it working, maybe not in the best
of possible ways. Will share sometime this weekend

El dj, 31 ag 2017 a les 20:20 Jason Taylor <notifications@github.com> va
escriure:

**Comment by carlesjove** [comment]
So here's how I got it to work:

```
// Make the log out button be a form
<%= button_to "Log Out", destroy_session_path, remote: true %>

class SessionsController
  # POST
  def destroy_session
    Devise.sign_out_all_scopes ? sign_out : sign_out(resource_name)
    redirect_to really_destroy_session_path
  end

  # GET
  def really_destroy_session
    if user_signed_in?
      redirect_to dashboard_path
    else
      # This will force the AuthenticationController in iOS code
      render nothing: true, status: 401
    end
  end
end
```

I had tried many different things, but problem was how to force a `401` status to be handled by the app's code and have the Log In screen start a Turbolinks session instead of having the Log In screen pushed to the view stack (which adds a Go Back button that we don't want). The only way I found to so do was by forcing a `GET` request after destroying the session.

**Comment by thetizzo** [comment]
Interesting.  I took a quick try at it today and got as far as the server side actually logging me out but the iOS side doesn't refresh the view and doesn't seem to process the 204 response that Devise sends back at all.  I'm hoping to find some time this weekend to dig in a little more.
