### ISSUE TITLE
Account Registration with Devise & Turbolinks

### ISSUE THREAD

**Issue by pbmarcano** [thetizzo/thetizzo.github.io#3]
Hey Jason,

Thanks for your [very helpful tutorial](https://thetizzo.com/howto/2016/10/03/authentication-with-devise-and-turbolinks-for-iOS) on logging in with devise on iOS.

I was wondering if you knew of any steps to enable account creation using devise.

When I try to create a new user with devise's sign up with the same methodology, the authentication view dismisses, does a get request, then receives a 401 and reappears.

It doesn't actually create an account server side.

If I add `remote: true`, the account gets created but the authentication form doesn't dismiss.

Wondering if you made it to this use case in your app or if you simply did a log in?

**Comment by thetizzo** [comment]
I haven't solved this scenario in my app yet (got distracted by working on other things).  

However, I expect your server side for this would need to sign in the user and then return the same status to the iOS side that you would after a successful normal sign in.  I'm not sure if Devise automatically signs the user in after account creation or not.

**Comment by pbmarcano** [comment]
![signupworks](https://user-images.githubusercontent.com/6471901/29939317-75996d1c-8e59-11e7-966e-101bf81e7e5f.gif)

From what I can tell, yes, signing up does automatically sign the user in on account creation.

I'll play around with `WKScriptMessageHandler` to attempt to dismiss the form after using `remote: true` on the sign up form... I'll let you know how I manage.
